spring:
  datasource:
    url: jdbc:postgresql://tinkoff-kotlin-psql-1.postgres.database.azure.com:5432/fintech?currentSchema=cashback
    username: kotlin_master@tinkoff-kotlin-psql-1
    password: koklin
  kafka:
    consumer:
      bootstrapServers: 40.69.78.245:19092
      groupId: cashback
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        request.timeout.ms: 20000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

paimentprocessing:
  services:
    uri:
      card: http://13.79.17.165/card-service/api/v1/card
      client: http://13.79.17.165/client-service/api/v1/client
      loyalty: http://13.79.17.165/loyalty-service/api/v1/program
      notification: http://13.79.17.165/notification-service/api/v2/client
  sign: erohin
  kafka:
    consumer:
      topic: transactions